### ISSUE TITLE
Windows Agent computed metrics should not reference Mongo

### ISSUE THREAD

**Issue by Grumblesmith** [metricly/metricly-docs#53]
https://docs.metricly.com/integrations/microsoft-sql/microsoft-sql-metrics/ references mongo metrics in the computed metric section, and doesn't appear to reference the actual computed metrics from https://github.com/netuitive-community-packages/netuitive-packages-windows/blob/dev/analyticConfigurations/computed_metric-windows.winsrv.json

**Comment by TheConnMan** [comment]
OBE
